### Numpy Basics

In [3]:
# we need to import the Numpy library
import numpy as np # by convention we call it np

In [4]:
# Numpy has its own data structures
my_arr = np.arange(3, 10) # an array-range can only contain the same data type
my_arr

array([3, 4, 5, 6, 7, 8, 9])

In [21]:
# arange is more performant when carrying out operations
my_l = list(my_arr)
# %time an operation on both the arange and the list
%time for i in range(100000): my_arr2 = my_arr*2 # multiply each value by 2
%time for i in range(100000): my_l2   = [x*2 for x in my_l]

CPU times: total: 46.9 ms
Wall time: 73.9 ms
CPU times: total: 125 ms
Wall time: 151 ms


### n-dimensional arrays

In [34]:
# we can create a two-dimensional array
data = np.random.randn(2,3)
data.shape
data.dtype # numpy adds new data types: float64, int32 etc.

dtype('float64')

In [35]:
data1 = [6,7,5,3,1]
arr1 = np.array(data1)
arr1.dtype

dtype('int32')

In [51]:
# we can populate an array automatically
z = np.zeros( (3,6) ) # these are floating-pointzero values
z
e = np.empty( (6,3) )
e # it is not empty - it points to 'empty' memory locations

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
# we can convert between data types
arr3 = arr1.astype(np.string_) # make all the values into string values
arr3

array([b'6', b'7', b'5', b'3', b'1'], dtype='|S11')

In [60]:
z = np.zeros( (3,3,3) ) # a three-by-three-by-three
z

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [65]:
# we can carry out maths on arrays
arr1**2
# we can carry out logic
arr1>3

array([ True,  True,  True, False, False])

In [71]:
# indexing and slicing is the same as all other Python ordinal collections
# [start:stop-before:step]
arr1[1:4] # 7, 5, 3

array([7, 5, 3])

In [73]:
# we can transpose an array
data.T # the rows and columns are switched

array([[ 1.08173891,  2.2793972 ],
       [-0.40378789,  0.49849798],
       [-0.68135135, -0.63092689]])